version: '3.4'

services:
  redis:
    image: redis
    container_name: redis_base_crud
    command: redis-server --requirepass Tratata101
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - /hdd/redis/base-crud/data/:/var/lib/redis/
#      - /hdd/redis/base-crud/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'

  crudserver:
    build: .
    container_name: base_crud
    volumes:
      - ./storage_gorm:/go/src/crud-server/storage_gorm
      - ./usersstorage:/go/src/crud-server/usersstorage
    ports:
      - '8081:8081'
    links:
      - redis
    depends_on:
      - redis
